"""initial phase one schema

Revision ID: a4e38234aa24
Revises:
Create Date: 2026-08-29 15:48:28.749541

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a4e38234aa24"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("project_type", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("district", sa.String(length=100), nullable=False),
        sa.Column(
            "status", sa.Enum("DRAFT", "ACTIVE", "COMPLETED", name="project_status"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_district"), "projects", ["district"], unique=False)
    op.create_index(op.f("ix_projects_state"), "projects", ["state"], unique=False)
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "LANDOWNER",
                "OFFICER",
                "PROJECT_AUTHORITY",
                "DISTRICT_ADMIN",
                "SENIOR_ADMIN",
                name="user_role",
            ),
            nullable=False,
        ),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("row_hash"),
    )
    op.create_index(op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False)
    op.create_table(
        "parcels",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("khasra_survey_no", sa.String(length=100), nullable=False),
        sa.Column(
            "polygon",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "khasra_survey_no"),
    )
    op.create_index(
        op.f("ix_parcels_khasra_survey_no"), "parcels", ["khasra_survey_no"], unique=False
    )
    op.create_table(
        "cases",
        sa.Column("parcel_id", sa.Uuid(), nullable=False),
        sa.Column(
            "current_stage",
            sa.Enum(
                "NOTIFICATION",
                "VERIFICATION",
                "OBJECTION",
                "AWARD",
                "COMPENSATION",
                "POSSESSION",
                name="case_stage",
            ),
            nullable=False,
        ),
        sa.Column("assigned_officer_id", sa.Uuid(), nullable=True),
        sa.Column("affected_family_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_officer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["parcel_id"], ["parcels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parcel_id"),
    )
    op.create_index(
        op.f("ix_cases_assigned_officer_id"), "cases", ["assigned_officer_id"], unique=False
    )
    op.create_index(op.f("ix_cases_current_stage"), "cases", ["current_stage"], unique=False)
    op.create_table(
        "landowners",
        sa.Column("parcel_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("contact", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["parcel_id"], ["parcels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "case_stage_history",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_stage",
            sa.Enum(
                "NOTIFICATION",
                "VERIFICATION",
                "OBJECTION",
                "AWARD",
                "COMPENSATION",
                "POSSESSION",
                name="case_stage",
            ),
            nullable=False,
        ),
        sa.Column(
            "to_stage",
            sa.Enum(
                "NOTIFICATION",
                "VERIFICATION",
                "OBJECTION",
                "AWARD",
                "COMPENSATION",
                "POSSESSION",
                name="case_stage",
            ),
            nullable=False,
        ),
        sa.Column("changed_by", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "compensation_status",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ASSESSED", "APPROVED", "DISBURSED", name="compensation_state"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
    )
    op.create_table(
        "documents",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_document_id", sa.Uuid(), nullable=True),
        sa.Column("file_url", sa.String(length=500), nullable=False),
        sa.Column("extracted_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "EXTRACTED", "VERIFIED", "REJECTED", name="document_status"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "version"),
    )
    op.create_table(
        "grievances",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("priority", sa.String(length=30), nullable=False),
        sa.Column("department", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "ASSIGNED", "RESOLVED", name="grievance_status"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rr_status",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("rehabilitation_stage", sa.String(length=100), nullable=False),
        sa.Column("resettlement_site_assigned", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rr_status")
    op.drop_table("grievances")
    op.drop_table("documents")
    op.drop_table("compensation_status")
    op.drop_table("case_stage_history")
    op.drop_table("landowners")
    op.drop_index(op.f("ix_cases_current_stage"), table_name="cases")
    op.drop_index(op.f("ix_cases_assigned_officer_id"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_parcels_khasra_survey_no"), table_name="parcels")
    op.drop_table("parcels")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_projects_state"), table_name="projects")
    op.drop_index(op.f("ix_projects_district"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
